In [1]:
import pandas as pd
import numpy as np
%matplotlib inline
from __future__ import print_function
import collections
import math
import os
import random
import tensorflow as tf
#import zipfile
from matplotlib import pylab
import matplotlib.pyplot as plt
from six.moves import range
from six.moves.urllib.request import urlretrieve
from sklearn.manifold import TSNE
import gensim

C:\Users\Yoni\AppData\Local\Continuum\anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
C:\Users\Yoni\AppData\Local\Continuum\anaconda3\lib\site-packages\gensim\utils.py:1197: UserWarning: detected Windows; aliasing chunkize to chunkize_serial
  warnings.warn("detected Windows; aliasing chunkize to chunkize_serial")


In [3]:
# Importing the dataset
dataset = pd.read_csv('001ssb.txt',header=None, delimiter = '\n', quoting = 3)
dataset.rename(columns={"0": "Lines_Numbers"})
dataset.head()

0
0                                 A Game Of Thrones 
1                Book One of A Song of Ice and Fire 
2                            By George R. R. Martin 
3                                          PROLOGUE 
4  "We should start back," Gared urged as the woo...

In [4]:
# Cleaning the texts
import re
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords
#from nltk.stem.porter import PorterStemmer
corpus = []
for i in range(0, dataset.size):
    line = re.sub('[^a-zA-Z]', ' ', dataset[0][i])
    line = line.lower()
    line = line.split()
    #ps = PorterStemmer()
    line = [word for word in line if not word in set(stopwords.words('english'))]
    line = ' '.join(line)
    corpus.append(line)


[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Yoni\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [15]:
len(corpus)
corpus

['brown fox jumped lazy dog', 'chicken cross road', 'like flying plane']

In [22]:
print(dataset[0][2])
print(corpus)

i like flying on a plane
['brown fox jumped lazy dog', 'chicken cross road', 'like flying plane']


In [17]:
# Creating the Bag of Words model
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()
X = cv.fit_transform(corpus).toarray()



In [35]:
print (len(cv.vocabulary_))
print(cv.get_feature_names())

11
CountVectorizer(analyzer='word', binary=False, decode_error='strict',
        dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
        lowercase=True, max_df=1.0, max_features=None, min_df=1,
        ngram_range=(1, 1), preprocessor=None, stop_words=None,
        strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
        tokenizer=None, vocabulary=None)
['brown', 'chicken', 'cross', 'dog', 'flying', 'fox', 'jumped', 'lazy', 'like', 'plane', 'road']


In [21]:
#one hot vectoer
print(X)

[[1 0 0 1 0 1 1 1 0 0 0]
 [0 1 1 0 0 0 0 0 0 0 1]
 [0 0 0 0 1 0 0 0 1 1 0]]


In [31]:
data = tf.keras.preprocessing.sequence.skipgrams(sequence=dataset,vocabulary_size=len(cv.vocabulary_),negative_samples=1,
                                          window_size=1, seed =5)


In [33]:
data

([], [])

0
0                                     A Game Of Thrones 
1                    Book One of A Song of Ice and Fire 
2                                By George R. R. Martin 
3                                              PROLOGUE 
4      "We should start back," Gared urged as the woo...
5                                                dead." 
6      "Do the dead frighten you?" Ser Waymar Royce a...
7      Gared did not rise to the bait. He was an old ...
8      "Dead is dead," he said. "We have no business ...
9      "Are they dead?" Royce asked softly. "What pro...
10     "Will saw them," Gared said. "If he says they ...
11     Will had known they would drag him into the qu...
12     than sooner. "My mother told me that dead men ...
13     "My wet nurse said the same thing, Will," Royc...
14     tit. There are things to be learned even from ...
15                                                     1
16     "We have a long ride before us," Gared pointed...
17     Ser Waymar Royce glanced at the sky with disin...
18                        unmanned by the dark, Gared?" 
19     Will could see the tightness around Gared's mo...
20     pressed anger in his eyes under the thick blac...
21     Night's Watch, man and boy, and he was not acc...
22     that. Under the wounded pride, Will could sens...
23     nervous tension that came perilous close to fe...
24     Will shared his unease. He had been four years...
25     the old stories had come rushing back, and his...
26     afterward. He was a veteran of a hundred rangi...
27     southron called the haunted forest had no more...
28     Until tonight. Something was different tonight...
29     rise. Nine days they had been riding, north an...
...                                                  ...
19568  through the firefall Dany heard women shriek a...
19569                      Only death can pay for life. 
19570  And there came a second crack, loud and sharp ...
19571  her and the pyre shifted, the logs exploding a...
19572  of frightened horses, and the voices of the Do...
19573  calling her name and cursing. No, she wanted t...
19574  The fire is mine. I am Daenerys Stormborn, dau...
19575  dragons, mother of dragons, don't you see? Don...
19576  reached thirty feet into the sky, the pyre col...
19577  forward into the firestorm, calling to her chi...
19578  The third crack was as loud and sharp as the b...
19579  When the fire died at last and the ground beca...
19580  her amidst the ashes, surrounded by blackened ...
19581  man and woman and stallion. She was naked, cov...
19582   hair all crisped away . . . yet she was unhurt. 
19583  The cream-and-gold dragon was suckling at her ...
19584  cradled them close. The black-and-scarlet beas...
19585  coiled under her chin. When it saw Jorah, it r...
19586                                                570
19587  Wordless, the knight fell to his knees. The me...
19588  lay his arakh at her feet. "Blood of my blood,...
19589  "Blood of my blood," she heard Aggo echo. "Blo...
19590  And after them came her handmaids, and then th...
19591  and Dany had only to look at their eyes to kno...
19592     forever, hers as they had never been Drogo's. 
19593  As Daenerys Targaryen rose to her feet, her bl...
19594  nostrils. The other two pulled away from her b...
19595  unfolding and stirring the air, and for the fi...
19596                                 music of dragons. 
19597                                                571

[19598 rows x 1 columns]

In [53]:
corpus = [
    'he is a king',
    'she is a queen',
    'he is a man',
    'she is a woman',
    'warsaw is poland capital',
    'berlin is germany capital',
    'paris is france capital',
]

In [39]:
def tokenize_corpus(corpus):
    tokens = [x.split() for x in corpus]
    return tokens

tokenized_corpus = tokenize_corpus(corpus)
print(tokenized_corpus)

[['he', 'is', 'a', 'king'], ['she', 'is', 'a', 'queen'], ['he', 'is', 'a', 'man'], ['she', 'is', 'a', 'woman'], ['warsaw', 'is', 'poland', 'capital'], ['berlin', 'is', 'germany', 'capital'], ['paris', 'is', 'france', 'capital']]


In [41]:
vocabulary = []
for sentence in tokenized_corpus:
    for token in sentence:
        if token not in vocabulary:
            vocabulary.append(token)

word2idx = {w: idx for (idx, w) in enumerate(vocabulary)}
idx2word = {idx: w for (idx, w) in enumerate(vocabulary)}

vocabulary_size = len(vocabulary)
print(word2idx)
print('############################')
print(idx2word)
print('############################')
print(vocabulary_size)

{'he': 0, 'is': 1, 'a': 2, 'king': 3, 'she': 4, 'queen': 5, 'man': 6, 'woman': 7, 'warsaw': 8, 'poland': 9, 'capital': 10, 'berlin': 11, 'germany': 12, 'paris': 13, 'france': 14}
############################
{0: 'he', 1: 'is', 2: 'a', 3: 'king', 4: 'she', 5: 'queen', 6: 'man', 7: 'woman', 8: 'warsaw', 9: 'poland', 10: 'capital', 11: 'berlin', 12: 'germany', 13: 'paris', 14: 'france'}
############################
15


In [42]:
window_size = 2
idx_pairs = []
# for each sentence
for sentence in tokenized_corpus:
    indices = [word2idx[word] for word in sentence]
    # for each word, threated as center word
    for center_word_pos in range(len(indices)):
        # for each window position
        for w in range(-window_size, window_size + 1):
            context_word_pos = center_word_pos + w
            # make soure not jump out sentence
            if context_word_pos < 0 or context_word_pos >= len(indices) or center_word_pos == context_word_pos:
                continue
            context_word_idx = indices[context_word_pos]
            idx_pairs.append((indices[center_word_pos], context_word_idx))

idx_pairs = np.array(idx_pairs) # it will be useful to have this as numpy array
print(idx_pairs)

[[ 0  1]
 [ 0  2]
 [ 1  0]
 [ 1  2]
 [ 1  3]
 [ 2  0]
 [ 2  1]
 [ 2  3]
 [ 3  1]
 [ 3  2]
 [ 4  1]
 [ 4  2]
 [ 1  4]
 [ 1  2]
 [ 1  5]
 [ 2  4]
 [ 2  1]
 [ 2  5]
 [ 5  1]
 [ 5  2]
 [ 0  1]
 [ 0  2]
 [ 1  0]
 [ 1  2]
 [ 1  6]
 [ 2  0]
 [ 2  1]
 [ 2  6]
 [ 6  1]
 [ 6  2]
 [ 4  1]
 [ 4  2]
 [ 1  4]
 [ 1  2]
 [ 1  7]
 [ 2  4]
 [ 2  1]
 [ 2  7]
 [ 7  1]
 [ 7  2]
 [ 8  1]
 [ 8  9]
 [ 1  8]
 [ 1  9]
 [ 1 10]
 [ 9  8]
 [ 9  1]
 [ 9 10]
 [10  1]
 [10  9]
 [11  1]
 [11 12]
 [ 1 11]
 [ 1 12]
 [ 1 10]
 [12 11]
 [12  1]
 [12 10]
 [10  1]
 [10 12]
 [13  1]
 [13 14]
 [ 1 13]
 [ 1 14]
 [ 1 10]
 [14 13]
 [14  1]
 [14 10]
 [10  1]
 [10 14]]


In [51]:
def get_input_layer(word_idx):
    x = torch.zeros(vocabulary_size).float()
    x[word_idx] = 1.0
    return x

In [52]:
embedding_dims = 5
W1 = Variable(torch.randn(embedding_dims, vocabulary_size).float(), requires_grad=True)
z1 = torch.matmul(W1, x)

NameError: name 'Variable' is not defined

In [ ]:
W2 = Variable(torch.randn(vocabulary_size, embedding_dims).float(), requires_grad=True)
z2 = torch.matmul(W2, z1)

In [ ]:
embedding_dims = 5
W1 = Variable(torch.randn(embedding_dims, vocabulary_size).float(), requires_grad=True)
W2 = Variable(torch.randn(vocabulary_size, embedding_dims).float(), requires_grad=True)
num_epochs = 100
learning_rate = 0.001

for epo in range(num_epochs):
    loss_val = 0
    for data, target in idx_pairs:
        x = Variable(get_input_layer(data)).float()
        y_true = Variable(torch.from_numpy(np.array([target])).long())

        z1 = torch.matmul(W1, x)
        z2 = torch.matmul(W2, z1)
    
        log_softmax = F.log_softmax(z2, dim=0)

        loss = F.nll_loss(log_softmax.view(1,-1), y_true)
        loss_val += loss.data[0]
        loss.backward()
        W1.data -= learning_rate * W1.grad.data
        W2.data -= learning_rate * W2.grad.data

        W1.grad.data.zero_()
        W2.grad.data.zero_()
    if epo % 10 == 0:    
        print(f'Loss at epo {epo}: {loss_val/len(idx_pairs)}')